codesarc_salesperson_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: CodesarcSalespersonPlugin:Greeting:staticallyGreet
        name: ~

codesarc_salesperson_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: CodesarcSalespersonPlugin:Greeting:dynamicallyGreet
        name: ~
